service: aws-bedrock-llm-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  apiGateway:
    apiKeys:
      - apiKey

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: /query
          private: true
          method: post
